### PR TITLE
Remove *-citadel/, now users can get them from pkg/ by using kpt

### PR DESCRIPTION
**Pull request by elfinhe**
Mesh CA:
```
kpt pkg get https://github.com/elfinhe/anthos-service-mesh-packages.git/asm .
```
Extra commands to use Citadel CA:
```
rm -rf asm/istio
kpt pkg get https://github.com/elfinhe/anthos-service-mesh-packages.git/pkg/istio-citadel asm/istio
```

### CODE REVIEW

**Comment by elfinhe** [comment]
ptal @yangminzhu

**Comment by elfinhe** [comment]
cc @yanyuan-meiyi

**Comment by yangminzhu** [comment]
this seems refactoring the istio-operator.yaml to a separate directory and download it again for citadel? better than duplicating the whole package, does this need any documentation update in the current flow?

**Comment by yangminzhu** [comment]
> > this seems refactoring the istio-operator.yaml to a separate directory and download it again for citadel? better than duplicating the whole package, does this need any documentation update in the current flow?
> 
> that's right. no change on the current asm flow.

I think we need a small change in the documentation for installation with istioctl because the path to the istio-operator.yaml is changed.

**Pull request merged**
