### PR TITLE
Add GKE WP enablement condition for unmanaged ASM

### PR DESCRIPTION
**Pull request by jasonwzm**
Avoid GKE WP validation error when Environ WP is being used.

### CODE REVIEW

**Review by zerobfd — CHANGES_REQUESTED** [review]
"GKE workload identity" isn't a product, and I'm pretty sure the plan is to move everything under the same WI anyways. The logic change is fine, but don't re-name anything.

**Comment by jasonwzm** [comment]
Good point. I removed the rename in the messages. But I'd still like to change the method names to make it clear for internal dev.

**Comment by zerobfd** [comment]
In that case use "svc" to match the workload pool name.

**Comment by jasonwzm** [comment]
Now that I think about it more, we may not need to differentiate WI then. Will keep it as it was.

**Review by zerobfd — APPROVED** [review]

**Pull request merged**
