### PR TITLE
rename the install_asm to asmcli

### PR DESCRIPTION
**Pull request by ZhengzheYang**

### CODE REVIEW

**Review by zerobfd — CHANGES_REQUESTED** [review]
Let's move the asmcli folder up to the root instead of putting it under scripts. Also, let's go ahead and rename cloudbuild-master to cloudbuild-main.

**Comment by ZhengzheYang** [comment]
need to update the cloudbuild yamls to cope with the renaming.

**Comment by ZhengzheYang** [comment]
@zerobfd The tests have passed. When you have time please take another look. Thanks!

**Review by zerobfd — APPROVED** [review]
Thanks!

**Pull request merged**
