### PR TITLE
Provide an istio dns service sample for VM's kubernetes name resolution 

### PR DESCRIPTION
**Pull request by jasonwzm**
GCP internal load balancer created for Kubernetes DNS.

### CODE REVIEW

**Comment by zerobfd** [comment]
If this is generally usable, I'd rather go back to #193 and merge it into master and then cherry-pick onto the release branches.

**Comment by elfinhe** [comment]
we'd better create this in master first.

**Comment by zerobfd** [comment]
Chatted offline. This is specific to a particular 1.7 feature, and in general isn't good practice. We decided to make that clearer by adding a comment to the file, and merging directly into the 1.7 release branch as an exception. This commit won't get put into master.

**Review by zerobfd — APPROVED** [review]
LGTM but I don't know much about the specifics of this service, if you want someone to review for correctness then request a review from them. Otherwise lmk and I'll merge.

**Comment by jasonwzm** [comment]
@maasen Can you review the comment in the file?

**Review by maasen — APPROVED** [review]
LGTM

**Review by elfinhe — APPROVED** [review]

**Pull request merged**
