### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by zerobfd**
This was officially removed a long time ago, finally cleaning up the code.

Also cleaning up a few trailing whitespace occurrences.

### CODE REVIEW

**Review by ZhengzheYang — COMMENTED** [review]
Did we make sure to coordinate with Eng Prod to get rid of the legacy MCP tests? Last time I checked there are a bunch. Also, did we make sure we have enough coverage with AFC/MCP on all the scenarios? Since I had to add privateCA tests with AFC myself last time, maybe there are more? (maybe not, not sure).

**Comment by zerobfd** [comment]
I talked to some individual folks about that but I didn't personally audit that they actually got removed. I'll follow up before this gets to release branches.

**Comment by ZhengzheYang** [comment]
Ok, note that the `master-asm` branch has a workflow to sync with the `main` branch commit, so merging this before cleaning up the tests will result in a lot of red on the `master-asm` test grid (in a few days, before the next successful sync).

**Comment by zerobfd** [comment]
That's what tests are for :) I think I've made the right people aware though. Thanks for bringing it up.

**Review by ZhengzheYang — APPROVED** [review]
LGTM with the awareness that this might break not-yet-removed tests.

**Pull request merged**
