### PR TITLE
Update CRD and CR

### PR DESCRIPTION
**Pull request by JimmyCYJ**

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
cc @liminwang @zerobfd

**Comment by JimmyCYJ** [comment]
cc @liminw @zerobfd

**Review by liminw — APPROVED** [review]

**Review by zerobfd — APPROVED** [review]
lgtm if @liminw says it's OK

**Comment by JimmyCYJ** [comment]
@zerobfd  @liminw has approved.

**Comment by JimmyCYJ** [comment]
@zerobfd  Thanks for reviewing this PR

**Pull request merged**
