### PR TITLE
Allow revisioned istiod to be exposed for discovery

### PR DESCRIPTION
**Pull request by jasonwzm**
Re-using the existing file so that multiproject multicluster setup can still use the same file.

Manually asking @nmittler for review. Nathan, can you also take a look at the change?

### CODE REVIEW

**Review by zerobfd — COMMENTED** [review]
When you tested this what did the kpt command look like? I thought if it were done like this you'd need to specify the entire name, instead of e.g. how we do the Service name where all you set via the cli is the revision tag and the value gets generated. See gke-hub-metadata for an example.

I'm not a `kpt` expert so this could be right right way.

**Comment by jasonwzm** [comment]
@zerobfd 
Here I am using entire value replacement. `kpt cfg set anthos.servicemesh.istiodHost istiod-asm-182-2.istio-system.svc.cluster.local` The reason is I still want multiproject setup to use the raw yaml, therefore I cannot use substitution. With substitution, that value on the yaml would look like `istiod-REV.istio-system.svc.cluster.local`.

@elfinhe Any thoughts on this? since you worked with kpt before.

**Comment by elfinhe** [comment]
> @zerobfd
> Here I am using entire value replacement. `kpt cfg set anthos.servicemesh.istiodHost istiod-asm-182-2.istio-system.svc.cluster.local` I still want multiproject setup to use the raw yaml, therefore I cannot use substitution. With substitution, that value on the yaml would look like `istiod-REV.istio-system.svc.cluster.local`.
> 
> @elfinhe Any thoughts on this? since you worked with kpt before.

what are the other alternative values of anthos.servicemesh.istiodHost? And what use cases are this istiod discovery used for, for connecting sidecars to istiod?

**Comment by jasonwzm** [comment]
> what are the other alternative values of anthos.servicemesh.istiodHost, need to support MCP? 

Yes and any remote or in-cluster istiod address.

> And what use cases are this istiod discovery used for, for connecting sidecars to istiod?

Yes and also service proxy agent and sds agent connecting to istiod.

**Comment by elfinhe** [comment]
> > what are the other alternative values of anthos.servicemesh.istiodHost, need to support MCP?
> 
> Yes and any remote or in-cluster istiod address.
> 
> > And what use cases are this istiod discovery used for, for connecting sidecars to istiod?
> 
> Yes and also service proxy agent and sds agent connecting to istiod.

LGTM. Thanks Jason.

I remembered that the istiod VS can only work for connections via the gateways, not other sidecars in the cluster (connecting to istiod during sidecar bootstrapping before envoy route rules take effect). I guess that is the case for vm. So looks good.

**Comment by jasonwzm** [comment]
@elfinhe Yes and you can see the gateway on the VS.

Can you also approve the PR? Adding you as a reviewer.

**Review by elfinhe — APPROVED** [review]

**Review by nmittler — APPROVED** [review]

**Pull request merged**
