### PR TITLE
Update mesh id.

### PR DESCRIPTION
**Pull request by elfinhe**

### CODE REVIEW

**Comment by elfinhe** [comment]
@djazayeri

**Comment by djazayeri** [comment]
Also need to change the mesh_id cluster label in cluster.yaml

**Comment by elfinhe** [comment]
> Also need to change the mesh_id cluster label in cluster.yaml

Nice catch, thanks!

**Comment by elfinhe** [comment]
```
taohe@taohe:~/elfinhe/anthos-service-mesh-packages$ cd "$(mktemp -d)"
taohe@taohe:/tmp/tmp.s84lEENUjd$ kpt pkg get https://github.com/elfinhe/anthos-service-mesh-packages.git/asm@up-mesh-id-146 .
fetching package /asm from https://github.com/elfinhe/anthos-service-mesh-packages to asm
taohe@taohe:/tmp/tmp.s84lEENUjd$ cat asm/cluster/istio-operator.yaml asm/cluster/cluster.yaml | grep "proj-"
      meshID: "proj-133206865343" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.project.projectNumber","value":"133206865343"}]}}
    mesh_id: "proj-133206865343" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.project.projectNumber","value":"133206865343"}]}}
```

**Pull request merged**
