### PR TITLE
ASM EKS/AKS In-cluster: essential option file

### PR DESCRIPTION
**Pull request by shankgan**
Ensures that Control plane certificate is self signed.

Option file only for in-cluster installations, not for MCP

### CODE REVIEW

**Comment by shankgan** [comment]
Tentative plan: use these option files for all configs absolutely required for ASM to come up with EKS/AKS

**Comment by shankgan** [comment]
Still in process of verification: more changes may be forthcoming

**Comment by zerobfd** [comment]
My only comment pre-verification: if we expect that one of (EKS, AKS) changing means the other will also change, then let's make them one file. Maybe we can add a softlink to the other file.

**Comment by jtrbs** [comment]
Test infra does not support EKS with k8s 1.22. I gave it a test on EKS with k8s 1.21. Worked fine for Mesh CA installation. 
```
2022-03-26T03:34:58.776538Z     info    done initializing workload trustBundle
2022-03-26T03:34:58.776555Z     info    initializing Istiod DNS certificates host: istiod-asm-1131-0.istio-system.svc, custom host: 
2022-03-26T03:34:58.872861Z     info    Generating istiod-signed cert for [istiod-asm-1131-0.istio-system.svc istiod.istio-system.svc istiod-remote.istio-system.svc istio-pilot.istio-system.svc]:
```
@zerobfd Yeah not sure how AKS will be different from EKS in the future. We can start with just one overlay. Maybe called `attached-cluster.yaml`. Currently I do not really know who is the platform owner for AKS or EKS.

**Comment by shankgan** [comment]
> Test infra does not support EKS with k8s 1.22. I gave it a test on EKS with k8s 1.21. Worked fine for Mesh CA installation.
> 
> ```
> 2022-03-26T03:34:58.776538Z     info    done initializing workload trustBundle
> 2022-03-26T03:34:58.776555Z     info    initializing Istiod DNS certificates host: istiod-asm-1131-0.istio-system.svc, custom host: 
> 2022-03-26T03:34:58.872861Z     info    Generating istiod-signed cert for [istiod-asm-1131-0.istio-system.svc istiod.istio-system.svc istiod-remote.istio-system.svc istio-pilot.istio-system.svc]:
> ```
> 
> @zerobfd Yeah not sure how AKS will be different from EKS in the future. We can start with just one overlay. Maybe called `attached-cluster.yaml`. Currently I do not really know who is the platform owner for AKS or EKS.

done - combined into attached-cluster.yaml

**Review by zerobfd — APPROVED** [review]

**Review by jtrbs — APPROVED** [review]

**Comment by jtrbs** [comment]
Could we get the change cherry-picked into 1.13 branch as well?

**Comment by shankgan** [comment]
> Could we get the change cherry-picked into 1.13 branch as well?
ack

**Pull request merged**
