### PR TITLE
enable cross cluster workload entry reading by default

### PR DESCRIPTION
**Pull request by stevenctl**

### CODE REVIEW

**Review by jasonwzm — CHANGES_REQUESTED** [review]
Also add to hub-meshca file. https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/istio/options/hub-meshca.yaml

**Review by jasonwzm — APPROVED** [review]
Thanks!

**Comment by stevenctl** [comment]
Is there something similar to `/retest` for this repo? I don't see anything in the logs for the one failure, and one says it needs a collaborator to trigger.

**Pull request merged**
