### PR TITLE
Verify cluster is registered to the expected Fleet

### PR DESCRIPTION
**Pull request by backward-compatible**

### CODE REVIEW

**Comment by backward-compatible** [comment]
This is how the negative testing outputs:

> 2021-08-20T21:47:08.207284 asmcli: Verifying cluster registration.
2021-08-20T21:47:08.426952 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/t27111d1079a4644/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:47:08.485478 asmcli: -------------
2021-08-20T21:47:08.949608 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/t27111d1079a4644/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:47:09.007677 asmcli: -------------
2021-08-20T21:47:11.414552 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/t27111d1079a4644/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:47:11.472758 asmcli: -------------
2021-08-20T21:47:11.925886 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/t27111d1079a4644/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:47:11.982601 asmcli: -------------
2021-08-20T21:47:13.174430 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/t27111d1079a4644/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
2021-08-20T21:47:13.231837 asmcli: -------------
2021-08-20T21:47:14.464532 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/t27111d1079a4644/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
2021-08-20T21:47:14.519598 asmcli: -------------
2021-08-20T21:47:18.142553 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
2021-08-20T21:47:18.201860 asmcli: -------------
2021-08-20T21:47:19.451035 asmcli: [ERROR]: Cluster is registered in the project tailorbird, but the required Fleet project is gzip-dev.
2021-08-20T21:47:19.451082 Please ensure that the cluster is registered to the gzip-dev project.
FAILED

**Comment by backward-compatible** [comment]
This is how the positive testing outputs:

> 2021-08-20T21:49:33.577846 asmcli: Verifying cluster registration.
2021-08-20T21:49:33.791286 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:49:33.844650 asmcli: -------------
2021-08-20T21:49:34.285605 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:49:34.345257 asmcli: -------------
2021-08-20T21:49:36.903908 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:49:36.959725 asmcli: -------------
2021-08-20T21:49:37.410738 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
2021-08-20T21:49:37.467474 asmcli: -------------
2021-08-20T21:49:38.629231 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
2021-08-20T21:49:38.691469 asmcli: -------------
2021-08-20T21:49:39.894984 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
2021-08-20T21:49:39.954052 asmcli: -------------
2021-08-20T21:49:43.613648 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
2021-08-20T21:49:43.670016 asmcli: -------------
2021-08-20T21:49:44.900280 asmcli: Verified cluster is registered to gzip-dev

**Comment by zerobfd** [comment]
> This is how the positive testing outputs:
> 
> > 2021-08-20T21:49:33.577846 asmcli: Verifying cluster registration.
> > 2021-08-20T21:49:33.791286 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > 2021-08-20T21:49:33.844650 asmcli: -------------
> > 2021-08-20T21:49:34.285605 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > 2021-08-20T21:49:34.345257 asmcli: -------------
> > 2021-08-20T21:49:36.903908 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > 2021-08-20T21:49:36.959725 asmcli: -------------
> > 2021-08-20T21:49:37.410738 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > 2021-08-20T21:49:37.467474 asmcli: -------------
> > 2021-08-20T21:49:38.629231 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
> > 2021-08-20T21:49:38.691469 asmcli: -------------
> > 2021-08-20T21:49:39.894984 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
> > 2021-08-20T21:49:39.954052 asmcli: -------------
> > 2021-08-20T21:49:43.613648 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
> > 2021-08-20T21:49:43.670016 asmcli: -------------
> > 2021-08-20T21:49:44.900280 asmcli: Verified cluster is registered to gzip-dev

Do you know why we're running the same command several times in a row?

**Comment by backward-compatible** [comment]
> > This is how the positive testing outputs:
> > > 2021-08-20T21:49:33.577846 asmcli: Verifying cluster registration.
> > > 2021-08-20T21:49:33.791286 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:33.844650 asmcli: -------------
> > > 2021-08-20T21:49:34.285605 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:34.345257 asmcli: -------------
> > > 2021-08-20T21:49:36.903908 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:36.959725 asmcli: -------------
> > > 2021-08-20T21:49:37.410738 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:37.467474 asmcli: -------------
> > > 2021-08-20T21:49:38.629231 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
> > > 2021-08-20T21:49:38.691469 asmcli: -------------
> > > 2021-08-20T21:49:39.894984 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
> > > 2021-08-20T21:49:39.954052 asmcli: -------------
> > > 2021-08-20T21:49:43.613648 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
> > > 2021-08-20T21:49:43.670016 asmcli: -------------
> > > 2021-08-20T21:49:44.900280 asmcli: Verified cluster is registered to gzip-dev
> 
> Do you know why we're running the same command several times in a row?

Not sure.. **retry** maybe?

**Comment by ZhengzheYang** [comment]
> > > This is how the positive testing outputs:
> > > > 2021-08-20T21:49:33.577846 asmcli: Verifying cluster registration.
> > > > 2021-08-20T21:49:33.791286 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > 2021-08-20T21:49:33.844650 asmcli: -------------
> > > > 2021-08-20T21:49:34.285605 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > 2021-08-20T21:49:34.345257 asmcli: -------------
> > > > 2021-08-20T21:49:36.903908 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > 2021-08-20T21:49:36.959725 asmcli: -------------
> > > > 2021-08-20T21:49:37.410738 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > 2021-08-20T21:49:37.467474 asmcli: -------------
> > > > 2021-08-20T21:49:38.629231 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
> > > > 2021-08-20T21:49:38.691469 asmcli: -------------
> > > > 2021-08-20T21:49:39.894984 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
> > > > 2021-08-20T21:49:39.954052 asmcli: -------------
> > > > 2021-08-20T21:49:43.613648 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
> > > > 2021-08-20T21:49:43.670016 asmcli: -------------
> > > > 2021-08-20T21:49:44.900280 asmcli: Verified cluster is registered to gzip-dev
> > 
> > 
> > Do you know why we're running the same command several times in a row?
> 
> Not sure.. **retry** maybe?

I think it's because we do have multiple commands stacked? https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/e7efa9d1bc23aed1b2388ac2c5315f06e5f22faf/asmcli/lib/checks.sh#L72-L83 here are some commands, and some commands are also called in https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/e7efa9d1bc23aed1b2388ac2c5315f06e5f22faf/asmcli/lib/checks.sh#L127-L138

**Comment by backward-compatible** [comment]
> > > > This is how the positive testing outputs:
> > > > > 2021-08-20T21:49:33.577846 asmcli: Verifying cluster registration.
> > > > > 2021-08-20T21:49:33.791286 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > > 2021-08-20T21:49:33.844650 asmcli: -------------
> > > > > 2021-08-20T21:49:34.285605 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > > 2021-08-20T21:49:34.345257 asmcli: -------------
> > > > > 2021-08-20T21:49:36.903908 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > > 2021-08-20T21:49:36.959725 asmcli: -------------
> > > > > 2021-08-20T21:49:37.410738 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > > > 2021-08-20T21:49:37.467474 asmcli: -------------
> > > > > 2021-08-20T21:49:38.629231 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
> > > > > 2021-08-20T21:49:38.691469 asmcli: -------------
> > > > > 2021-08-20T21:49:39.894984 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
> > > > > 2021-08-20T21:49:39.954052 asmcli: -------------
> > > > > 2021-08-20T21:49:43.613648 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
> > > > > 2021-08-20T21:49:43.670016 asmcli: -------------
> > > > > 2021-08-20T21:49:44.900280 asmcli: Verified cluster is registered to gzip-dev
> > > 
> > > 
> > > Do you know why we're running the same command several times in a row?
> > 
> > 
> > Not sure.. **retry** maybe?
> 
> I think it's because we do have multiple commands stacked?
> 
> https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/e7efa9d1bc23aed1b2388ac2c5315f06e5f22faf/asmcli/lib/checks.sh#L72-L83
> 
> here are some commands, and some commands are also called in
> https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/e7efa9d1bc23aed1b2388ac2c5315f06e5f22faf/asmcli/lib/checks.sh#L127-L138

Yeah just noticed at least 2 of those can be squeezed into one. I'll do that.

**Comment by backward-compatible** [comment]
> > This is how the positive testing outputs:
> > > 2021-08-20T21:49:33.577846 asmcli: Verifying cluster registration.
> > > 2021-08-20T21:49:33.791286 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:33.844650 asmcli: -------------
> > > 2021-08-20T21:49:34.285605 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:34.345257 asmcli: -------------
> > > 2021-08-20T21:49:36.903908 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get crd memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:36.959725 asmcli: -------------
> > > 2021-08-20T21:49:37.410738 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io -ojsonpath={..metadata.name}'
> > > 2021-08-20T21:49:37.467474 asmcli: -------------
> > > 2021-08-20T21:49:38.629231 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=json'
> > > 2021-08-20T21:49:38.691469 asmcli: -------------
> > > 2021-08-20T21:49:39.894984 asmcli: Running: '/usr/bin/kubectl --kubeconfig /usr/local/google/home/gzip/tb/onprem/.kubetest2-syllogi/tdafbe71b09f46ca/user-kubeconfig.yaml --context cluster get memberships.hub.gke.io membership -o=jsonpath={.spec.identity_provider}'
> > > 2021-08-20T21:49:39.954052 asmcli: -------------
> > > 2021-08-20T21:49:43.613648 asmcli: Running: '/usr/local/google/home/gzip/google-cloud-sdk/bin/gcloud container hub memberships list --project gzip-dev --format=json'
> > > 2021-08-20T21:49:43.670016 asmcli: -------------
> > > 2021-08-20T21:49:44.900280 asmcli: Verified cluster is registered to gzip-dev
> 
> Do you know why we're running the same command several times in a row?

Some redundancy occurs due to **is_membership_crd_installed** check being decoupled into it's own boolean check (as a  short circuit). Other's I'll move to single command.

**Pull request closed without merging**
