### PR TITLE
adding git as a client dependency

### PR DESCRIPTION
**Pull request by sce-taid**

### CODE REVIEW

**Review by zerobfd — CHANGES_REQUESTED** [review]
Thank you for the PR! The `asmcli` tool is generated from other files and usually isn't edited directly. In this case since it's a small change, if you just make the same edit to `asmcli/lib/validate.sh` then it should work. More details on the dev process are in the docs/ folder if you're interested.

**Comment by sce-taid** [comment]
Hi,
github-asm-pkg-script-updated-main (asm-scriptaro-oss) is failing; could you have a look (e.g., at CB logs).
Thanks!

**Comment by zerobfd** [comment]
Hello! It's failing because the change is now in validate.sh but not asmcli. The change should be in both of them. You had the correct change in the original PR, it just *also* needed to be in validate.sh.

**Comment by sce-taid** [comment]
understood :) - thanks!

**Review by zerobfd — APPROVED** [review]

**Comment by zerobfd** [comment]
Thanks for the PR and all of the iterations!

**Pull request merged**
