### PR TITLE
Migrate ValidatingWebhookConfiguration to v1

### PR DESCRIPTION
**Pull request by sergii-ssh**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by sergii-ssh** [comment]
@howardjohn thanks for approving. Could you add `/gcbrun` comment to launch the tests?

**Comment by zerobfd** [comment]
Why is this just going into the legacy branch?

**Comment by sergii-ssh** [comment]
it is already updated in main and non-legacy 1.11 branches

**Comment by zerobfd** [comment]
The test that was failing isn't working on legacy anymore so I'm merging since I manually confirmed everything else works.

**Comment by sergii-ssh** [comment]
thank you Clay!

**Pull request merged**
