### PR TITLE
Use Hub WIP as default

### PR DESCRIPTION
**Pull request by jtrbs**
1. Combine hub-meshca overlay together with istio-operator. 
2. Use Hub WIP as default.

### CODE REVIEW

**Comment by jtrbs** [comment]
Take over https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/814

**Comment by shankgan** [comment]
quick q: Does this assume that every cluster where this script installs ASM is registered to a fleet that has Hub workload Identity turned on?

**Comment by jtrbs** [comment]
Hi @shankgan, 
For baremetal and onprem, the fleet registration is a prerequisite before executing asmcli.
For GKE-on-GCP
- If it can be registered (--enable-all or --enable-registration or --vm), asmcli will help register the cluster if it has not been registered. 
- If it cannot be registered with asmcli and it has no hub regisration, GKE WIP will be used.

**Review by zerobfd — APPROVED** [review]
LGTM. This change works with both MeshCA and Citadel off of GCP, right?

**Comment by jtrbs** [comment]
Hi @zerobfd, yeah this does not impact off GCP installation. For of GCP, I have tested both MeshCA and Citadel.

**Pull request merged**
