### PR TITLE
Fix option flags being ignored issue when reinstalling on an existing…

### PR DESCRIPTION
**Pull request by elfinhe**
Cherry pick of #434

- Fix option flags being ignored issues when reinstalling on an existing folder

### CODE REVIEW

**Comment by zerobfd** [comment]
Let's hold off on this one for a bit since there's a few more bug fixes coming

**Comment by elfinhe** [comment]
> Let's hold off on this one for a bit since there's a few more bug fixes coming

@zerobfd you mean we do not merge this PR, or we don't add a new release tag on this commit?

**Comment by zerobfd** [comment]
Not merge this PR. In general I'd like to follow one merge commit -> one release. That way we know that all of the commits in a release were in staging at the same time and tested together.

**Comment by elfinhe** [comment]
This PR was in staging-1.8-asm. Closing without merging.

**Pull request closed without merging**
